export const ACTIONS = {
	SET_TODO_INPUTS: 'SET_TODO_INPUTS',
	EDIT_TODO_INPUTS: 'EDIT_TODO_INPUTS',
	CLEAR_TODO_INPUTS: 'CLEAR_TODO_INPUTS',
	ADD_TODO_ITEM: 'ADD_TODO_ITEM',
	UPDATE_TODO_ITEM: 'UPDATE_TODO_ITEM',
	DELETE_TODO_ITEM: 'DELETE_TODO_ITEM',
	SET_CHECKED_STATE: 'SET_CHECKED_STATE',
	SET_CHECKED_ITEMS: 'SET_CHECKED_ID',
	SET_EDIT_STATE: 'SET_EDIT_STATE',
	SET_EDIT_TARGET: 'SET_EDIT_ITEM',
};
